import type { House } from "./types"

export const houses: House[] = [
  {
    id: "house1",
    name: "Lote 03",
    image: "/images/front_armando.png",
    floorPlan: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e",
    currentCameras: [
      { id: "cam1", name: "Entrada principal", type: "Hikvision", isNew: false, position: { x: 20, y: 15 }, coverage: 40 },
      { id: "cam2", name: "Entrada interna", type: "Hikvision", isNew: false, position: { x: 80, y: 80 }, coverage: 60 },
      { id: "cam3", name: "Lateral izquierdo", type: "Hikvision", isNew: false, position: { x: 10, y: 40 }, coverage: 50 },
      { id: "cam4", name: "Fondo playa", type: "Hikvision", isNew: false, position: { x: 5, y: 60 }, coverage: 60 },
      { id: "cam5", name: "Parrillero", type: "Hikvision", isNew: false, position: { x: 95, y: 60 }, coverage: 60 },
      { id: "cam6", name: "Hacia la piscina", type: "Hikvision", isNew: false, position: { x: 10, y: 10 }, coverage: 40 },
      { id: "cam7", name: "Arriba estudio Paula hacia la ruta", type: "Hikvision", isNew: false, position: { x: 90, y: 10 }, coverage: 70 },
      { id: "cam8", name: "Arriba estudio Paula hacia el mar", type: "Hikvision", isNew: false, position: { x: 50, y: 90 }, coverage: 70 },
    ],
    newCameras: [
      {
        id: "cam1",
        name: "Entrada principal",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 20, y: 15 },
        coverage: 100,
      },
      {
        id: "cam2",
        name: "Lateral izquierdo",
        type: "AI Turret",
        isNew: true,
        position: { x: 80, y: 80 },
        coverage: 100,
      },
      {
        id: "cam3",
        name: "Esquina playa izquierda",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 85, y: 30 },
        coverage: 100,
      },
      {
        id: "cam4",
        name: "Lateral playa interno izquierdo",
        type: "AI Pro",
        isNew: true,
        position: { x: 30, y: 40 },
        coverage: 100,
      },
      {
        id: "cam5",
        name: "Esquina playa exterior derecho",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 95, y: 60 },
        coverage: 100,
      },
      {
        id: "cam6",
        name: "Patio interno",
        type: "null",
        isNew: true,
        position: { x: 5, y: 60 },
        coverage: 100,
      },
      {
        id: "cam7",
        name: "Diagonal playa",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 90, y: 10 },
        coverage: 100,
      },
      {
        id: "cam8",
        name: "Diagonal ruta",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 50, y: 90 },
        coverage: 100,
      },
      {
        id: "cam9",
        name: "Diagonal playa",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 10, y: 40 },
        coverage: 100,
      },
      {
        id: "cam10",
        name: "Estudio Paula frente",
        type: "AI Turret",
        isNew: true,
        position: { x: 10, y: 10 },
        coverage: 100,
      },
    ],
  },
  {
    id: "house2",
    name: "Lote 04",
    image: "/images/front_medio.png",
    floorPlan: "/images/medio_plano.png", // Updated to use local image
    currentCameras: [
      {
        id: "cam1",
        name: "Frente en la esquina",
        type: "Hikvision",
        isNew: false,
        position: { x: 25, y: 20 },
        coverage: 55,
      },
      {
        id: "cam2",
        name: "Lateral izquierdo 1",
        type: "Hikvision",
        isNew: false,
        position: { x: 75, y: 85 },
        coverage: 55,
      },
      {
        id: "cam3",
        name: "Lateral izquierdo 2",
        type: "Hikvision",
        isNew: false,
        position: { x: 15, y: 50 },
        coverage: 60,
      },
      {
        id: "cam4",
        name: "Parrillero",
        type: "Hikvision",
        isNew: false,
        position: { x: 85, y: 40 },
        coverage: 50,
      },
      {
        id: "cam5",
        name: "Esquina interna",
        type: "Hikvision",
        isNew: false,
        position: { x: 50, y: 70 },
        coverage: 45,
      },
      {
        id: "cam6",
        name: "Externa ",
        type: "Hikvision",
        isNew: false,
        position: { x: 50, y: 70 },
        coverage: 45,
      },
      {
        id: "cam7",
        name: "Esquina entrada ",
        type: "Hikvision",
        isNew: false,
        position: { x: 50, y: 70 },
        coverage: 45,
      },
    ],
    newCameras: [
      {
        id: "cam1",
        name: "Entrada principal",
        type: "AI Turret",
        isNew: true,
        position: { x: 25, y: 20 },
        coverage: 100,
      },
      {
        id: "cam2",
        name: "Esquina ruta",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 75, y: 85 },
        coverage: 100,
      },
      {
        id: "cam3",
        name: "Muro playa",
        type: "AI Turret",
        isNew: true,
        position: { x: 15, y: 50 },
        coverage: 100,
      },
      {
        id: "cam4",
        name: "Parrillero",
        type: "AI Turret",
        isNew: true,
        position: { x: 85, y: 40 },
        coverage: 100,
      },
      {
        id: "cam5",
        name: "Esquina interna",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 50, y: 70 },
        coverage: 100,
      },
      {
        id: "cam6",
        name: "Pasillo subsuelo",
        type: "AI Pro",
        isNew: true,
        position: { x: 50, y: 70 },
        coverage: 100,
      },
      {
        id: "cam7",
        name: "Planta alta playa",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 50, y: 70 },
        coverage: 100,
      },
      {
        id: "cam8",
        name: "Planta alta ruta",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 50, y: 70 },
        coverage: 100,
      },
      
    ],
  },
  {
    id: "house3",
    name: "Lote 06",
    image: "/images/front_final.png",
    floorPlan: "/images/nido_plano.png",
    currentCameras: [
      {
        id: "cam1",
        name: "Lateral izquierdo",
        type: "Hikvision",
        isNew: false,
        position: { x: 30, y: 15 },
        coverage: 60,
      },
      {
        id: "cam2",
        name: "Lateral medio",
        type: "Hikvision",
        isNew: false,
        position: { x: 70, y: 80 },
        coverage: 60,
      },
      {
        id: "cam3",
        name: "Esquina interna",
        type: "Hikvision",
        isNew: false,
        position: { x: 80, y: 60 },
        coverage: 60,
      },
      {
        id: "cam4",
        name: "Esquina derecha",
        type: "Hikvision",
        isNew: false,
        position: { x: 15, y: 60 },
        coverage: 55,
      },
      {
        id: "cam5",
        name: "Fondo contra playa",
        type: "Hikvision",
        isNew: false,
        position: { x: 50, y: 85 },
        coverage: 55,
      },
      {
        id: "cam6",
        name: "Esquina lateral derecha",
        type: "Hikvision",
        isNew: false,
        position: { x: 40, y: 30 },
        coverage: 50,
      },
      {
        id: "cam7",
        name: "Esquina frente",
        type: "Hikvision",
        isNew: false,
        position: { x: 20, y: 25 },
        coverage: 55,
      },
      
    ],
    newCameras: [
      {
        id: "cam1",
        name: "Entrada principal",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 30, y: 15 },
        coverage: 100,
      },
      {
        id: "cam2",
        name: "Entrada arriba",
        type: "AI Turret",
        isNew: true,
        position: { x: 70, y: 80 },
        coverage: 100,
      },
      {
        id: "cam3",
        name: "Lateral izquierdo",
        type: "AI Turret",
        isNew: true,
        position: { x: 80, y: 60 },
        coverage: 100,
      },
      {
        id: "cam4",
        name: "Lateral medio",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 15, y: 60 },
        coverage: 100,
      },
      {
        id: "cam5",
        name: "Muro contra playa",
        type: "AI Turret",
        isNew: true,
        position: { x: 50, y: 85 },
        coverage: 100,
      },
      {
        id: "cam6",
        name: "Parrillero",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 40, y: 30 },
        coverage: 100,
      },
      {
        id: "cam7",
        name: "Esquina playa",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 20, y: 25 },
        coverage: 100,
      },
      {
        id: "cam8",
        name: "Esquina ruta",
        type: "AI Pro",
        isNew: true,
        position: { x: 60, y: 20 },
        coverage: 100,
      },
      {
        id: "cam9",
        name: "Arriba diagonal playa",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 65, y: 45 },
        coverage: 100,
      },
      {
        id: "cam10",
        name: "Arriba diagonal ruta",
        type: "G5 PTZ",
        isNew: true,
        position: { x: 35, y: 10 },
        coverage: 100,
      },
    ],
  },
]
